apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaling-lunch-rush-backend-reader
  namespace: scaling-lunch-rush
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
