apiVersion: v1
kind: Service
metadata:
  name: scaling-lunch-rush-backend
  namespace: scaling-lunch-rush
  labels:
    app: scaling-lunch-rush-backend
spec:
  type: ClusterIP
  selector:
    app: scaling-lunch-rush-backend
  ports:
    - name: http
      protocol: TCP
      port: 3001
      targetPort: 3001
